### ISSUE TITLE
Get material-design-lite from npm

### ISSUE THREAD

**Issue by rmachielse** [mike-north/ember-material-lite#261]
Hi!

We are using ember-material-lite in a project that uses ember-engines.
Currently bower dependencies are not supported, while npm dependencies are.
Getting material-design-lite from npm might be cleaner anyway, as the user doesn't have to add it to it's bower dependencies or package manually (so it can be removed from the blueprint as well).

Would you be open to a pr for this?

**Comment by rmachielse** [comment]
In case anyone is interested, I have given it a go here:

https://github.com/mike-north/ember-material-lite/compare/master...feedbackfruits:feature/byebyebower

**Comment by rmachielse** [comment]
@mike-north are you interested in this?

**Comment by mike-north** [comment]
@rmachielse yes

**Comment by rmachielse** [comment]
@mike-north #336
