### ISSUE TITLE
Error with 'ember generate' during installation step

### ISSUE THREAD

**Issue by zoamel** [mike-north/ember-material-lite#29]
I tried to install this addon via 'ember install ember-material-lite' command, and during installation I get this error:
```
$ ember install ember-material-lite
version: 1.13.5
Installed packages for tooling via npm.
installing ember-material-lite
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.
```

**Comment by truenorth** [comment]
Try
```sh
ember generate ember-material-lite <your app name>
```

**Comment by zoamel** [comment]
It did the jobs, thanks.

**Comment by mike-north** [comment]
this is more of an ember-cli issue than an issue with this addon.

**Comment by trabus** [comment]
@mike-north This is actually due to the blueprint not containing an override for normalizeEntityName. I've wanted to fix this for a while, but I don't have an immediate solution. So I'm going to make a PR to add the override for the time being. ;)
