### ISSUE TITLE
Error when using mdl-tabs

### ISSUE THREAD

**Issue by stavarotti** [mike-north/ember-material-lite#30]
__Problem:__

Getting the following module import error when using `mdl-tabs`:

```js
Uncaught Error: Could not find module `ember-composability/mixins/parent-component-support` imported from `ember-material-lite/components/mdl-tabs`
```

__Steps to reproduce__:

- $ ember new material-app
- $ ember install ember-material-lite
- $ ember generate ember-material-lite material-app
- Copy the `mdl-tabs` example from the demo site into `application.hbs`:
```hbs
{{#mdl-tabs active='Fruit'}}
  {{#mdl-tab title='Fruit'}}
    This is the fruit tab
  {{/mdl-tab}}
  {{#mdl-tab title='Vegetables'}}
    This is the vegetables tab
  {{/mdl-tab}}
{{/mdl-tabs}}
```
- $ ember s

__Solutions tried__

I tried adding `ember-composability` to the consuming application however, I get the following helper not found error:

```js
Uncaught Error: Assertion Failed: A helper named 'eq' could not be found
```

__Environment:__

```bash
OS -> OSX 10.10.4
ember-cli -> 1.13.6
ember -> 1.13.5
```

**Comment by mike-north** [comment]
Please try adding `ember-truth-helpers` to your project. Sorry for the bugs in the blueprint -- I'll get it fixed ASAP so nobody else gets snagged -- and thanks for your patience

**Comment by stavarotti** [comment]
That worked.  Thanks.

**Comment by mike-north** [comment]
I fixed the blueprint in https://github.com/mike-north/ember-material-lite/commit/860899e52ff70f0e09d3061a9bb6d12913c50f5e. which will go out in the next release
