### ISSUE TITLE
Radio buttons do not trigger properly

### ISSUE THREAD

**Issue by sunil-shrestha** [mike-north/ember-material-lite#32]
Clicking on radio buttons causes js error "Uncaught TypeError: Cannot read property 'updateClasses_' of undefined" and thus, it has no effect. The error can be fround in demo site also.

**Comment by mike-north** [comment]
ember version?

**Comment by sunil-shrestha** [comment]
I am using it with following versions

    Ember           : 1.13.4
    Ember Data      : 1.13.5
    jQuery          : 1.11.3
The same issue can be found at [demo site] (http://mike.works/ember-material-lite/#/toggles) also

**Comment by mike-north** [comment]
release `v0.1.4` now has the fix for this
