### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by alexjp** [mike-north/ember-material-lite#35]
Hi,

I installed ember-material-lite on a new project today.
I ran the generating of the blueprint and followed install like in other issues here. Everything seemed to be working, but I could not get any icons !

The theming and components worked, but no icons nowhere.

**Comment by mike-north** [comment]
Did you follow the last step here ( https://github.com/mike-north/ember-material-lite/issues/8#issuecomment-121304744 ) and add the `link` to your `index.html`?

**Comment by mike-north** [comment]
Do you have a repo that demonstrates this problem? It's hard to debug when I can't reproduce :)

**Comment by alexjp** [comment]
damn sorry !

have been so used to do it, that i forgot that step !!! :(

invalid bug report !!!!

**Comment by mike-north** [comment]
@alexjp no problem. Please let me know if you encounter any other issues
