### ISSUE TITLE
Radio button printing fixed name 'options'

### ISSUE THREAD

**Issue by henriquecf** [mike-north/ember-material-lite#45]
Hello, do not no why but the radio button component is printing a fixed name='options'

```
{{input type="radio" id=_inputId class="mdl-radio__button" name="options" value=value disabled=disabled}}
```

**Comment by henriquecf** [comment]
Nevermind. The name chages. But I am not able to bind it to a null controller value as usual

**Comment by mike-north** [comment]
@henriquecf what's the use case for a null `name` value? It's the means of grouping a set of choices together as a mutually-exclusive set
