### ISSUE TITLE
Table component is rendering as many sets of colums as number of rows.

### ISSUE THREAD

**Issue by kushdilip** [mike-north/ember-material-lite#50]
`mdl-table` has a bug which renders columns equivalent of `(number of columns) * (number of rows)`. 

Please have a look here http://mike.works/ember-material-lite/#/table

In `mdl-table.hbs` template each helper is actually triggering the init of mixin class multiple times.. 
```
	{{#each content as |row|}}
	<tr>
		{{yield row}}
	</tr>
	{{/each}}
```

**Comment by mannu150** [comment]
I am also facing the same issue.

**Comment by mike-north** [comment]
Make sure you update your ember-composability to `~0.1.3`

**Comment by mike-north** [comment]
Should have a bug fix for this today

**Comment by kushdilip** [comment]
:+1: 
@mike-north I have already updated ember-composability to  `~0.1.3`.

**Comment by mike-north** [comment]
This has now been fixed, and a new version has been tagged. Please update to:
```js
'ember-material-lite', '~0.1.8',
'ember-composability', '~0.2.0',
```

**Comment by kushdilip** [comment]
It works now. thanks.

**Comment by almazzi** [comment]
{{#mdl-table content=computedFields as |s|}}
  {{#mdl-table-col label=s.ru }}{{/mdl-table-col}}
{{/mdl-table}} 
here , I want to show only one row with certain cells but under first cell there column is appearing , how to show only one row with colunms

**Comment by harisadam** [comment]
this problem persists for me on v0.2.2 and composability v0.3.7. 
It is a pagination component, so I'm using query params:

https://www.dropbox.com/s/r9rtr847iqc5odx/material-table.mov?dl=0
