### ISSUE TITLE
Button type attribute

### ISSUE THREAD

**Issue by pranksinatra** [mike-north/ember-material-lite#60]
It'd be nice to be able to set the `{{mdl-button}}` type attribute. Currently, if this component is inside a `<form>` tag it will trigger a form submit, resulting in an array of side effects (such as page reloads) even if the component's action is handled. 

The HTML solution is setting `type="button"` on the `<button>` tag, which causes it to no longer submit forms. `<button>` default type [varies by browser](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) (submit | reset | button), but `type="button"` is probably the safest default. 

On the `{{mdl-button}}`, this just means adding "type" to `attributeBindings` with a default value of "button".

**Comment by mike-north** [comment]
released in `0.1.13`
