### ISSUE TITLE
maintaining this and ember-cli-materialize?

### ISSUE THREAD

**Issue by jamesdixon** [mike-north/ember-material-lite#76]
Hey @mike-north - saw that you currently have projects to support MDL and MaterializeCSS. Was just curious if you planned on maintaining both going forward or were committing to one vs the other? I started off with Ember Paper, but it seems to be dying, and unfortunately, my project is using bootstrap, so MaterializeCSS isn't a good fit. MDL seems to fit the bill, but just wanted to understand your plans with this project before I jumped into it. 

Thanks!

**Comment by 20v100** [comment]
https://github.com/mike-north/ember-material-lite/issues/28

**Comment by jamesdixon** [comment]
thanks @20v100 !
