### ISSUE TITLE
Error when using mdl-menu

### ISSUE THREAD

**Issue by Hirtenknogger** [mike-north/ember-material-lite#84]
When i copy the mdl-menu example in my application i get an error.

The mdl-menu example:
{{#mdl-menu}}
  {{#mdl-menu-item action='menuItemClicked' age=36}}Age: 36{{/mdl-menu-item}}
  {{#mdl-menu-item action='menuItemClicked' age=42}}Age: 42{{/mdl-menu-item}}
  {{#mdl-menu-item action='menuItemClicked' age=71}}Age: 71{{/mdl-menu-item}}
{{/mdl-menu}}

Error:
Could not find module `ember-composability/mixins/parent-component-support` imported from `ember-material-lite/components/mdl-menu`

**Comment by Hirtenknogger** [comment]
updating 'ember-composability' to version '0.2.1' solved it.

**Comment by cimtico** [comment]
I'm getting a bad position of the opened menu

**Comment by mike-north** [comment]
@cimtico - sounds like a potentially unrelated issue

**Comment by Hirtenknogger** [comment]
Have you tried it that way?
{{#mdl-menu align='unaligned'}}
...
{{/mdl-menu}}

**Comment by KurtRMueller** [comment]
@Hirtenknogger, I'm getting this error as well. I only have `ember-material-lite` installed however. 

I wonder if this error is due to the fact that in this repo's `bower.json` file, `ember-composability` is listed as a dev dependency.

**Comment by KurtRMueller** [comment]
Yea, when I install `ember-composability` as a dev dependency, the problem goes away.
