### ISSUE TITLE
I think I missed a step

### ISSUE THREAD

**Issue by CheoWalker** [mike-north/ember-material-lite#96]
After installing the addon and running ember generate ember-material-lite,  I get this error message: "Uncaught Error: Assertion Failed: A helper named 'mdl-item' could not be found." I think I missed a step but I just not sure where.

**Comment by patrickberkeley** [comment]
@CheoWalker maybe try restarting your server?

**Comment by CheoWalker** [comment]
I did restart the server. Still the issue persist.

**Comment by patrickberkeley** [comment]
Actually looking at what you originally posted, I don't think there's an `mdl-item` component. There's [`mdl-menu-item`](https://github.com/mike-north/ember-material-lite/blob/master/addon/components/mdl-menu-item.js).

**Comment by CheoWalker** [comment]
Sorry the original error was mdl-nav:
{{#mdl-nav title='DZ Web Creations' scrollHeader=true}}
    {{mdl-item name='Work' route='work'}}
{{/mdl-nav}}
{{outlet}}

I created a helper mdl-nav to fix the error, but then the mdl-item error appeared.

**Comment by patrickberkeley** [comment]
Okay yeah there's also an `mdl-nav-item` component. Do you get the error if you reference that?

```hbs
{{#mdl-nav title='DZ Web Creations' scrollHeader=true}}
  {{mdl-nav-item name='Work' route='work'}}
{{/mdl-nav}}
{{outlet}}
```

Still, you shouldn't have to create your own `mdl-nav` component.

**Comment by CheoWalker** [comment]
No, the error with mdl-nav prevent the mdl-nav-item from trying to render.

**Comment by CheoWalker** [comment]
Running "ember generate ember-material-lite <your app name>" seems to fix the issue with mdl-nav, but I am still having the mdl-nav-item issue.

**Comment by CheoWalker** [comment]
Reset the server and now everything seems to be working fine.
